apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: load-generator
  name: load-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
      - name: load-generator
        image: busybox:1.28        
        args:
          - /bin/sh
          - -c
          - while sleep 0.01; do wget -q -O- http://php-apache; done
